### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-search-backend#11]
Agregar logs al servicio.

Tomar de referencia los de los otros proyectos de BioTablero, la idea es que se registren las peticiones, respuestas y errores.

Tener en cuenta que los errores no deben ser retornado en la respuesta del API, pero sí se deben registrar en el archivo de logs.

Consideraciones

Poner logs a la ruta get_layer_by_polygon y organizar la configuración de los logs en el archivo config.

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-search-backend/11?planning-poker) with Zenhub @cazapatamar @ManuelStardust

**Comment by ManuelStardust** [comment]
Se realizó una primera revisión para la implementación de los logs y se socializó con el equipo de desarrollo. Se modificó el alcance de la tarea según los resultados de la socialización.

**Comment by ManuelStardust** [comment]
Se hizó una implementación de logs para el endpoint get_layer_by_polygon logrando almacenar logs para eventos de consulta, respuesta y errores de servidor. Sin embargo para errores de petición y validación no se lograron implementar para un endpoint específico, por tanto se hizo una implementación para la captura de este tipo de errores de forma transversal en la aplicación aprovechando el manejo de excepciones de Fast API.
