### ISSUE TITLE
Agregar middleware para logs de peticiones

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-search-backend#14]
# Descripción

Agregar un middleware para los logs de las peticiones. Se debe registrar tanto cuando llega la petición como cuando se responde, y debe incluir, en ambos casos, el id de la petición y la url completa

# Consideraciones
https://fastapi.tiangolo.com/tutorial/middleware/

**Comment by ManuelStardust** [comment]
Se implemento un middleware para capturar las peticiones y respuestas, se socializo con Erika para aclarar algunas dudas. Estoy terminando de hacer pruebas de la implementación para subir el PR.
