### ISSUE TITLE
Manejo de errores

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-search-backend#15]
# Descripción
Terminar la implementación del manejo de errores que inició Manuel cuando implementó los logs. El requerimiento es que los errores que se produzcan en la aplicación queden en el archivo de log pero el mensaje que se retorne finalmente en el endpoint sea más "genérico" (que no incluya detalles)

Creo que lo mejor es que los dejemos elevar como lo hacíamos con el antiguo backend (la mayoría se loguea en el manejador de errores/excepciones, en las capas inferiores solo se loguean vlaidaciones manuales). Igualmente sería bueno verificar si hay otra estrategia que debamos considerar, así que darle un tiempo y tratamiento de spike a esta tarea, pero igual se espera la implementación como resultado.

Agregar al documento de los proyectos en python la información relevante con la estrategia a seguir

# Consideraciones
- https://fastapi.tiangolo.com/tutorial/handling-errors/#override-the-default-exception-handlers
- https://fastapi.tiangolo.com/how-to/custom-request-and-route/?h=logging#accessing-the-request-body-in-an-exception-handler

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-search-backend/15?planning-poker) with Zenhub @cazapatamar @denarch22

**Comment by cazapatamar** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-search-backend/15?planning-poker) with Zenhub @ManuelStardust

**Comment by denarch22** [comment]
Se realiza la respectiva revisión de la metodología a implementar, dejando la información en el documento, aunque me inclino mas por la segunda opción ya que hay varios métodos que internamente manejan los errores y pues son errores muy específicos de la operación que se esta realizando.
[Manejo de Excepciones en FastAPI.docx](https://docs.google.com/document/d/1iwPDSSSK6G3Fl91UtU6fYz1ZRtT2HqzJ/edit?usp=drive_link&ouid=114621074878060025658&rtpof=true&sd=true)

**Comment by erikasv** [comment]
@denarch22 subir el documento al drive del equipo, y como dice la tarea:
1. Incluir al documento de los proyectos en python la estrategia que se debe seguir
2. Hacer los ajustes necesarios a la implementación (se espera un PR)

**Comment by erikasv** [comment]
@denarch22 favor tener en cuenta lo siguiente dentro del alcance de esta tarea:

El [log](https://github.com/PEM-Humboldt/biotablero-search-backend/blob/develop/app/middleware/exception_handlers.py#L11) que se hace de la excepción en el manejador de excepciones deja my poca información para algunos errores, por favor guardar en el log algo más del traceback de la excepción (por ejemplo usando `traceback.print_exc()`)

**Comment by erikasv** [comment]
@denarch22 no tengo comentarios adicionales sobre el documento, puedes esperar los comentario de @cazapatamar y @ManuelStardust hasta finalizar el día. Una vez hagas los ajustes a la implementación, colocar en el documento de proyectos en python, en la sección `Manejo de errores` la estrategia implementada, nada de código de ejemplo, solo la descripción de lo que se decidió implementar

**Comment by cazapatamar** [comment]
Inicialmente cuando leí el documento me sonó mas la idea de tener un unico manejador de excepciones, pensando en centralizar esta logica y poder mantenerlo mas fácilmente, pero luego leyendo el comentario de @denarch22 creo que es algo importante a tener en cuenta lo que menciona que para dar manejo a algunos tipos de errores puede llegar a ser algo muy especifico entonces creo que la opción 2 es correcta.

**Comment by ManuelStardust** [comment]
Estoy de acuerdo con la opción 2, creo que nos sirve más manejar los tipos de excepciones de forma separada.

**Comment by erikasv** [comment]
@denarch22 Por favor tener en cuenta que los errores también se tienen que retornar en json, actualmente se están retornando en texto plano
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGhrQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2223402e44fa5ddd75bbbadb8908b8ab666d7a6b/imagen.png" alt="imagen.png" />
