### ISSUE TITLE
Validación para el bbox

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-search-backend#18]
# Descripción

Agregar la validación para que la propiedad bbox de los polígonos sea obligatoria.

Si no se puede a través de geojson_pydantic, hacerlo con otro método.

# Consideraciones
- Esquema del polígono: https://github.com/PEM-Humboldt/biotablero-search-backend/blob/dataEndpoint/app/routes/schemas/polygon.py

# Actualización 15/07

Agregar al readme el comando para formatear y para verificar el formato del código

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-search-backend/18?planning-poker) with Zenhub @cazapatamar @denarch22 @ManuelStardust

**Comment by denarch22** [comment]
Se realiza la revisión de la tarea y se presenta inconvenientes con la librería schemajson, sin embargo, en validaciones con el equipo se estaba abordando otro proyecto, por lo que se retomara la tarea con el proyecto adecuado

**Comment by denarch22** [comment]
Se realiza ajuste del código, pero al realizar pruebas presentaba error en el main, se verifica que hubo una actualización en la rama develop en las horas de la tarde, por lo que fue necesario volver a reajustar el código, se están realizando las pruebas de las modificaciones.

**Comment by denarch22** [comment]
Se realiza el PR para su respectiva revisión según lo comentado esta mañana: https://github.com/PEM-Humboldt/biotablero-search-backend/pull/22

**Comment by denarch22** [comment]
Se realiza el MR según los cambios aprobados.
