### ISSUE TITLE
Pruebas sobre las áreas del polígono

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-search-backend#21]
# Descripción

Probar los valores del endpoint `POST /metrics/{metric_id}/areas`. Para esto:

- Cargar al STAC uno de los raster que están en este momento en el servidor de biab de biotablero, solo el de un periodo cualquiera para perdida y persistencia
- Cambiar la url que se está quemando en el código en este momento por el cog del raster cargado en el paso anterior
- Hacer un ajuste temporal en el front para imprimir en consola el polígono que se dibuja en el módulo de consultas en formato geojson, debe incluir el bbox o imprimirlo aparte (o si resulta complejo, usar [esta página](https://geojson.io/#map=5.56/3.56/-73.98) para sacar el bbox).
- Dibujar un polígono en biotablero y tomar ese mismo polígono para las pruebas con el nuevo backend. Comparar los resultados

# Consideraciones

El ajuste temporal al front debe hacerse en una rama aparte para poder compartirla con los demás miembors del equipo, pero no es algo que se vaya a mezclar

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-search-backend/21?planning-poker) with Zenhub @cazapatamar @denarch22 @ManuelStardust

**Comment by ManuelStardust** [comment]
- Se realizó la carga al STAC Server de la [capa](https://staccatalog.blob.core.windows.net/cog-test/Colombia_pp-2015_2011_test_areas.tif) con la que actualmente se trabaja en el servidor de Biab para el cálculo de perdida y persistencia para el periódo 2011-2015.
- Se creó la rama [testPolygon](https://github.com/PEM-Humboldt/biotablero-frontend/tree/testPolygon) para imprimir en consola un poligono digujado en formato geojson incluyendo el bbox.
- Se realizaron pruebas con diferentes polígonos y se compararon los resultados entre lo obtenido en el script de Biab y la implementación en python. 
- Adicionalmente se compararon los resultados para el área del departamento de Risaralda usando el polígono actualmente usado en Biotablero, y se comparo con los resultados obtenidos en Biotablero para áreas definidas.
Los resultados anteriores se consignan en una [hoja de cálculo](https://docs.google.com/spreadsheets/d/1NnLYSpwW-uyEbWwCLxeGuyVkssIVK0wluEPz3ha51bA/edit?usp=sharing).

**Comment by ManuelStardust** [comment]
Se realizaron pruebas con el script actual en el servidor de Biab a una resolución de 30m. Los resultados muestras cálculos mas cercanos entre los dos métodos, sin embargo parece que las capas resultantes con el script en Biab presentan una rotación y reflejo horizontal.
