### ISSUE TITLE
Reorganización de main

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-search-backend#24]
# Descripción

De acuerdo a lo discutido en la tarea [23](https://github.com/PEM-Humboldt/biotablero-search-backend/issues/23) vamos a reorganizar un poco el repositorio:

- crear una carpeta `utils` dentro de la carpeta `app`
- meter dentro de esa carpeta el archivo `context_vars.py`
- crear dentro de esa carpeta archivos para el middleware de los logs y para el manejo de excepciones, mover la lógica actualmente en main para allá
- mover el archivo config a esa carpeta

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-search-backend/24?planning-poker) with Zenhub @denarch22 @cazapatamar

**Comment by denarch22** [comment]
Se realiza el respectivo ajuste de los métodos del manejador de excepciones según las recomendaciones realizadas en la tarea, se genera el PR: 
https://github.com/PEM-Humboldt/biotablero-search-backend/pull/30

Quedo atenta a cualquier comentario.

**Comment by denarch22** [comment]
Se realiza los respectivos ajustes indicados en los comentarios del PR y se realoza el MR
