### ISSUE TITLE
Traer colecciones desde el servidor stac

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-search-backend#26]
# Descripción

Reemplazar las colecciones quemadas en el servicio `metrics` por la lógica correspondiente para traer la información correspondiente del servidor stac.

Seguramente en este momento no hay ninguna colección cargada con el id `LossPersistence`, cargar una con todos los periodos que le corresponden.

[Aquí](https://drive.google.com/drive/folders/1GeRaxxcAo3fuX165a35CCkuJl2Ezxlse) están los archivos necesarios para cargar la colección. Cambiar el id en la especificación.

Por ahora seleccionar el primer item de la colección para extraer el archivo cog y seguir retornando resultados.

La lógica de la función `get_layer_by_polygon` para extraer la información de la colección es la misma que para la función `get_areas_by_polygon`, hacer los ajustes necesarios para que `get_areas_by_polygon` reciba el id de la métrica también.

# Consideraciones
- Resolver los TODO relacionados

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-search-backend/26?planning-poker) with Zenhub @cazapatamar @denarch22

**Comment by denarch22** [comment]
Se realiza el MR según las correcciones y aprobación realizadas.
