### ISSUE TITLE
Consultar todos los periodos para métrica LossPersistence

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-search-backend#29]
# Descripción

Terminar de implementar el endpoint que trae los valores de áreas para LossPersistence.

Lo primero que se debe hacer es renombrar el endpoint a `/{metric_id}/values` (recordemos que el objetivo es usar ese endpoint para todas las métricas del módulo de consultas, así que, como no siempre se retornan áreas, es mejor retornar "values")

Esta tarea corresponde a calcular las áreas para todos los periodos (items) de la colección LossPersistence (cargada en la tarea [26](https://github.com/PEM-Humboldt/biotablero-search-backend/issues/26)) y retornar un arreglo de objetos como respuesta al endpoint. El formato en el que se deben retornar es:

```json
[
  {
    "periodo": "2016-2021",
    "persistencia": 50000,
    "perdida": 15000,
    "no_bosque": 10000
  },
  {
    "periodo": "2016-2021",
    "persistencia": 163080.04683781133,
    "perdida": 1577.360253916899,
    "no_bosque": 192213.66467893738
  },
  ...
]
```

**Comment by cazapatamar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-search-backend/29?planning-poker) with Zenhub @denarch22 @ManuelStardust
