### ISSUE TITLE
[spike] optimización de cálculo de áreas

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-search-backend#37]
# Descripción

La función `get_raster_values` es demasiado lenta, cuando se revisaron los valores de las áreas calculadas se identificó que el problema radica en la función que hace la proyección de la capa (que debido a la librería, es la misma que hace el [corte](https://github.com/PEM-Humboldt/biotablero-search-backend/blob/develop/app/services/utils/raster.py#L28) con el polígono)

Debemos encontrar la forma de que el endpoint responda más rápido, al menos la mitad del tiempo, para esto se debe contemplar las siguientes opciones: 
- volver a revisar la librería zonal-statistics (revisada en la tarea [12](https://github.com/PEM-Humboldt/biotablero-search-backend/issues/12))
- Verificar si con rio-tiler se puede este corte y proyección de otra forma más eficiente
- buscar otras opciones.

# Actualización 11/09
Dejar en una rama diferente cada implementación

**Comment by denarch22** [comment]
Se realizo una pequeña investigación sobre las opciones a implementar las cuales se encuentran el archivo drive, https://docs.google.com/document/d/1h-Jw9GRB6oHjcXpPDdaQGG-itMjxiVsQ/edit?usp=drive_link, adicional he estado haciendo pruebas de las opciones de paralelismo usando las librería de concurrent y dask , los cuales bajaron a 21 y 22 segundos correspondientemente, estoy realizando pruebas actualmente con la librería rasterstats, la cual estoy presentando dificultades con la reproyeccion ya que están quedando datos muy pequeños en las áreas categóricas de respuestas

**Comment by denarch22** [comment]
Se realizo la verificación con paralelismo usando concurrent y dask, para la primera opción se valido que el tiempo bajo a 21 segundos, y dask quedo en 22 segundos por lo que en el repositorio deje la primera opción, para la librería de rasterstats, se identifico que aunque ya categoriza los valores la reproyección no esta quedando bien por lo que se esta haciendo manual y es necesario explorar otras librerías, por lo que en el momento se continuara con las otras opciones.

**Comment by denarch22** [comment]
El dia de ayer estaba verificando cual era la mejor opción para realizar la reproyección ya que me di cuenta que no importaba que librería usara si no estaba bien reproyectado no iban a dar los resultados, entonces tome un enfoque diferente y decidí dedicarme solo a verificar la reproyeccion,me di cuenta igualmente que realizar la reproyección manual estaba produciendo inconsistencias por lo que decidi replicar de una mejor manera la funcion de cog.features, lo logre con la librería de rioxarray realizando primero el recorte del raste en el crs original con rio.clip y reproyectando al crs destino, se logro reducir mas de un segundo y medio con esto,ahora la demora persiste en la extraccion de las geometrias y valores ya que encontre que hay geometrias con valores nulos y son necesarias filtrar, intente varias formas pero demoran casi lo mismo con un list comprehension ,paralelismo,numpy,dask ,tengo pendiente la opcion con zonal stats pero esta me pide guardar el raster o en memoria o en disco, también intente la opción de earth engine,pero según las nuevas políticas de google la ejecución individual externa ya no es posible, es necesario que el proyecto de encuentre en gcp para poder inicializarse en el ingreso del motor engine

**Comment by denarch22** [comment]
Realice el ajuste del método con zonal_stats donde evidencie que ya los datos son consistentes y su ejecución son de 10 segundos aproximadamente este es la rama donde queda la implementación: https://github.com/PEM-Humboldt/biotablero-search-backend/tree/rasterOptimizationZonalStatistics
