### ISSUE TITLE
Ruta de ejecución y diagrama E-R para "cache" de resultados

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-search-backend#38]
# Descripción

Hace alguna semanas exploramos varias posibilidades para optimizar las consultas de endpoints internamente relacionados, por ejemplo, evitar que hacer todo el proceso desde la descarga del raster cuando se consultas las áreas (endpoint `/values`) y las capas (endpoint `/layer`).

No es en sí mismo una cache, pero  es la mejor forma de describirlo. Las diferentes opciones que contemplamos están en [este documento](https://docs.google.com/document/d/1pRs3KqhBRN7G4ChbgDudSJRPIwOkA9NUvuUwaAM8zdk/edit#heading=h.3c9v9tgb03qg).

El objetivo de esta tarea es tener una ruta de implementación de la solución seleccionada (opción 2), y ampliación del diagrama E-R, de tal forma que incluya también las áreas de consulta definidas, un id o hash para el polígono, entre otros detalles más.

# Actualización al 02/10/2024

De acuerdo a la reunión tenida el viernes 27 de septiembre con el arquitecto de la gerencia de TI, se acordó elaborar un diagrama de arquitectura para discutir con él los servicios específicos que utilizaríamos para la base de datos de BioTablero.

**Comment by dev-juanzb-humboldt** [comment]
1. **DynamoDB (AWS)**:
   - Utilizar DynamoDB como base de datos no relacional para almacenar los cortes en formato JSON y facilitar las consultas rápidas sobre áreas específicas.

2. **Caché para raster**:
   - Implementar un sistema de caché para almacenar temporalmente los cortes procesados, mejorando el tiempo de respuesta en consultas repetidas.

3. **PostGIS**:
   - Utilizar PostGIS sobre PostgreSQL para gestionar polígonos y realizar consultas espaciales complejas, aprovechando sus capacidades geoespaciales avanzadas.

**Comment by dev-juanzb-humboldt** [comment]
Se realiza el E-R de la base de datos PostGIS para la optimización en las consultas al STAC para obtener información que puede repetirse.

https://docs.google.com/document/d/1dnEXp5BvVKdwVbjsPZYbulupw7Zx6UQ8/edit
