### ISSUE TITLE
Agregar sistema de migraciones

### ISSUE THREAD

**Issue by dev-juanzb-humboldt** [PEM-Humboldt/biotablero-search-backend#44]
**Descripción:**
Agregar un sistema de migraciones en el backend de Search del proyecto BioTablero. El objetivo es facilitar el control de versionamiento de las tablas, esquemas y objetos de la base de datos, permitiendo un despliegue sencillo en diferentes ambientes. Este sistema asegurará que los cambios en la base de datos se manejen de manera organizada y reproducible, mejorando la estabilidad y la trazabilidad en cada entorno.

**Criterios de aceptación:**

- El sistema de migraciones debe permitir realizar y revertir cambios en el esquema de la base de datos.

- Los cambios en la base de datos deben poder ser desplegados automáticamente en todos los entornos sin intervención manual.

- Documentación clara y completa para el equipo de desarrollo sobre el uso de las migraciones.

**Comment by dev-juanzb-humboldt** [comment]
The implementations corresponding to the migrations and control of the database were performed.

I share the PR for review.

https://github.com/PEM-Humboldt/biotablero-search-backend/pull/50

**Comment by dev-juanzb-humboldt** [comment]
Buenos días, ya realicé los cambios en el sistema de migraciones, pido el favor se revisen y se lleven lo nuevo a sus ramas para ver si todo está bien.

Muchas gracias :)

**Comment by erikasv** [comment]
El desarrollo de la tarea abarca mucho más del alcance. No se mezcla, usar de referencia.
