### ISSUE TITLE
Configurar LocalStack en proyecto Biotablero-search

### ISSUE THREAD

**Issue by dev-juanzb-humboldt** [PEM-Humboldt/biotablero-search-backend#46]
Se requiere configurar LocalStack para simular los servicios de AWS en los entornos locales de los desarrolladores. El objetivo es que cualquier desarrollador que clone el repositorio pueda ejecutar LocalStack de manera sencilla y realizar despliegues locales de la infraestructura y la aplicación FastAPI utilizando AWS CDK. La configuración debe ser fácil de replicar en diferentes máquinas de desarrollo utilizando herramientas como Docker Compose para iniciar LocalStack y scripts que automaticen el proceso de despliegue en el entorno simulado.

**Criterios de Aceptación**

- La configuración de LocalStack debe estar completamente integrada en el repositorio, de manera que los desarrolladores puedan clonar el repositorio y ejecutar LocalStack con un solo comando (por ejemplo, docker-compose up).

- Se debe incluir un archivo docker-compose.yml que inicie LocalStack y los servicios necesarios (Lambda, API Gateway, S3, etc.).

- Los desarrolladores deben poder desplegar el stack de AWS CDK en LocalStack usando comandos sencillos.

- La configuración debe ser completamente documentada en el README del proyecto, con instrucciones claras para los desarrolladores sobre cómo ejecutar LocalStack y realizar despliegues locales.

- Incluir scripts o makefiles para simplificar los comandos de despliegue y uso de CDK con LocalStack.

**Comment by erikasv** [comment]
No se mezcla, usar de referencia
