### ISSUE TITLE
Documentación global sobre el uso de los servicios en Biotablero-Search (FastAPI) y sus justificaciones

### ISSUE THREAD

**Issue by dev-juanzb-humboldt** [PEM-Humboldt/biotablero-search-backend#47]
Se requiere la creación de una documentación clara y comprensible que explique el uso de los servicios clave en el proyecto Biotablero-Search y el por qué detrás de la elección de cada uno de ellos. La documentación debe estar enfocada en facilitar el entendimiento global del equipo, explicando cómo cada servicio (Mangum, LocalStack, GitHub Actions, AWS CDK, entre otros) se integra y aporta beneficios al flujo de trabajo. El objetivo es proporcionar un recurso centralizado que ayude a todos los desarrolladores a entender la arquitectura del proyecto y las decisiones tecnológicas tomadas.

**Dependencias:**

- Conocimiento completo sobre cómo estos servicios están siendo utilizados en el proyecto actual.
- Comprensión de los beneficios específicos de cada herramienta y servicio en el contexto del proyecto.

**Actualización 30/10/2024**

Incluir y hacer explicito en el documento un análisis y propuesta de implementación de localstack como un componente no altamente acoplado al proyecto de biotablero-search haciendo una comparación con la implementación actual que se trabajó en otra tarea (donde si está muy acoplado), determinando ventajes y desventajas de cada uno. Se puede apoyar en diagramas o recursos que considere necesarios.

**Comment by cazapatamar** [comment]
@dev-juanzb-humboldt por fa asignarle el repo correcto a esta tarea ya que quedó asociado a biomodelos

**Comment by dev-juanzb-humboldt** [comment]
I developed a simple document to explain the different services and how they would be integrated within each app starting with biotablero - search service. 

I will deepen this one today, so that it is better detailed, but I share what I have written.

https://docs.google.com/document/d/1cAxH7HMVLzSEBX2xxWN4DgSyOzdErGMzl17e35AmnGU/edit?usp=sharing

**Comment by dev-juanzb-humboldt** [comment]
Buenos días, se hicierón cambios en el documento, para que por favor, puedan darle un vistazo, muchas gracias. 

https://docs.google.com/document/d/1cAxH7HMVLzSEBX2xxWN4DgSyOzdErGMzl17e35AmnGU/edit?usp=sharing

**Comment by dev-juanzb-humboldt** [comment]
Buenos días, se hicierón cambios en el documento, para que por favor, puedan darle un vistazo, muchas gracias.

https://docs.google.com/document/d/1cAxH7HMVLzSEBX2xxWN4DgSyOzdErGMzl17e35AmnGU/edit?usp=sharing

@cazapatamar @ManuelStardust

**Comment by dev-juanzb-humboldt** [comment]
Buenas tardes, realicé unas modificaciones en el documento global sobre los servicios, mejore los diagramas y los separé por capas, ya que así será facil de comprender, la parte del localstack y aws es como debería verse y funcionar, pero según lo desarrollado, podrá estár sujeto a algunos cambios. 

https://docs.google.com/document/d/1cAxH7HMVLzSEBX2xxWN4DgSyOzdErGMzl17e35AmnGU/edit?usp=sharing

Agradezco mucho al equipo para que lo puedan leer y estoy atento a sugerencias. 

@cazapatamar @erikasv @ManuelStardust @denarch22

**Comment by erikasv** [comment]
Se cambia el objetivo del documento y se deja de referencia
