### ISSUE TITLE
Asignar colores y categorías a partir de los datos en el stac

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-search-backend#48]
# Descripción 

Hacer los ajustes necesarios para que los colores asignados a las capas y las categorías de los valores sean leídos desde las propiedades cargadas en el stac.

**Comment by denarch22** [comment]
Se realiza el respectivo ajuste y se realiza el PR, Camilo solicito un ajuste en la colección la cual se realizo y se verifico, por lo tanto se realizo el MR según su aprobación.
