### ISSUE TITLE
Agregar action de pryright

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-search-backend#52]
# Descripción

Agregar un paso al workflow de github actions para la validación de tipos. Se recomienda usar pyright: https://github.com/microsoft/pylance-release/issues/4927#issuecomment-1832819120

Tanto el archivo como el workflow deben cambiar de nombre (que no sea especifico a un tipo de validación).

Se deben corregir en esta misma tarea todos los errores de tipado, solo en casos muy específicos se puede ignorar el error (como se estaba haciendo en el archivo `raster.py`)

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-search-backend/52?planning-poker) with Zenhub @cazapatamar @denarch22 @ManuelStardust

**Comment by ManuelStardust** [comment]
Se esta presentando un error en la validación de tipos al leer los raster con rioxarray.open_rasterio ya que puede entregar tipos Dataset y List[Dataset], en este caso pyright espera que se entregue un Dataset y por tanto es necesario extraer la primera banda del raster, sin embargo al hacer esto consume toda la memoria y no finaliza el proceso.
