### ISSUE TITLE
[Spike] Seleccionar librerías para el manejo de la base de datos y las migraciones

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-search-backend#54]
# Descripción

Realizar una pequeña investigación sobre el manejo de las migraciones y acceso a la base de datos desde python. Hacer una pequeña comparación entre algunas opciones y seleccionar una opción.

# Consideraciones
Con migraciones nos referimos por ahora exclusivamente la estructura de las tablas que requiere el backend para funcionar (por ejemplo que en un futuro se puedan actualizar las modificaciones a la estructura sin tener que volver a crear la base de datos)

**Comment by erikasv** [comment]
@denarch22 porfa subes el archivo donde hiciste al comparación a esta [carpeta](https://drive.google.com/drive/folders/1dqgI6qJhchupQAHwBSLE0va6u7eyZWqh)

**Comment by denarch22** [comment]
Se sube el archivo con la investigación realizada sobre las librerías en la carpeta indicada, adjunto el link del archivo:
https://docs.google.com/document/d/1pYa575B_3FQcT-oD2J1pW2nHUFKKOjv4/edit?usp=drive_link&ouid=114621074878060025658&rtpof=true&sd=true
